"""Offline-only signed capture-receipt verification for BridgeAgent.

No network, file I/O, signing in production, or Civil NX access. This verifies
consistency with independently pinned witness identity, NOT actual execution.
The receipt MUST be generated by an independent capture service, not BridgeAgent.
Never log or persist raw HTTP request bytes: they may contain MAPI credentials.
"""
from __future__ import annotations

import hashlib
import hmac
from datetime import timedelta
from typing import Any, AbstractSet

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from independent_attestation import _utc, verify_all
from offline_result_certifier import canonical_bytes, digest

FIELDS = frozenset({
    'schema_version', 'event', 'capture_id', 'collector_id',
    'model_sha256', 'authorization_id', 'analysis_run_id',
    'signed_analysis_attestation_sha256', 'raw_request_sha256',
    'raw_response_sha256', 'sent_at', 'received_at',
    'http_status', 'method', 'path'
})


def signed_attestation_hash(attestation: dict, signature_hex: str) -> str:
    """Binds signed record *and* its exact signature, not just event content."""
    return digest(canonical_bytes(attestation) + bytes.fromhex(signature_hex))


def verify_capture_receipt(
    envelope: dict, raw_request: bytes, raw_response: bytes,
    analysis_attestation: dict, analysis_signature_hex: str,
    receipt: dict, receipt_signature_hex: str,
    pinned_collector_id: str, pinned_capture_public_key: bytes,
    pinned_analysis_public_key: bytes, *,
    previously_seen_capture_ids: AbstractSet[str] = frozenset(),
    max_capture_duration_seconds: int = 300,
) -> dict:
    reasons: list[str] = []
    if not isinstance(receipt, dict):
        return {'status': 'HOLD', 'reasons': ['CAPTURE_RECEIPT_NOT_OBJECT']}
    if set(receipt) != FIELDS:
        reasons.append('CAPTURE_RECEIPT_SCHEMA_MISMATCH')
    if receipt.get('schema_version') != 1 or receipt.get('event') != 'CIVIL_NX_RESULT_CAPTURED':
        reasons.append('CAPTURE_RECEIPT_EVENT_INVALID')
    capture_id = receipt.get('capture_id')
    if not isinstance(capture_id, str) or not capture_id.strip() or len(capture_id) > 128:
        reasons.append('CAPTURE_ID_INVALID')
    elif capture_id in previously_seen_capture_ids:
        reasons.append('CAPTURE_REPLAY_DETECTED')
    if not isinstance(pinned_collector_id, str) or not pinned_collector_id or receipt.get('collector_id') != pinned_collector_id:
        reasons.append('CAPTURE_COLLECTOR_ID_UNTRUSTED')
    if not isinstance(pinned_capture_public_key, bytes) or len(pinned_capture_public_key) != 32:
        reasons.append('CAPTURE_TRUST_ANCHOR_NOT_PINNED')
    elif not isinstance(pinned_analysis_public_key, bytes) or len(pinned_analysis_public_key) != 32:
        reasons.append('ANALYSIS_TRUST_ANCHOR_NOT_PINNED')
    elif hmac.compare_digest(pinned_capture_public_key, pinned_analysis_public_key):
        reasons.append('CAPTURE_WITNESS_NOT_INDEPENDENT')

    try:
        sig = bytes.fromhex(receipt_signature_hex)
        if len(sig) != 64:
            raise ValueError('invalid signature length')
        if not isinstance(pinned_capture_public_key, bytes) or len(pinned_capture_public_key) != 32:
            raise ValueError('no pinned witness key')
        Ed25519PublicKey.from_public_bytes(pinned_capture_public_key).verify(sig, canonical_bytes(receipt))
    except (InvalidSignature, ValueError, TypeError, OverflowError):
        reasons.append('CAPTURE_SIGNATURE_INVALID')

    expected = {
        'model_sha256': envelope.get('model_evidence', {}).get('sha256'),
        'authorization_id': envelope.get('authorization', {}).get('authorization_id'),
        'analysis_run_id': envelope.get('analysis', {}).get('run_id'),
        'raw_request_sha256': digest(raw_request),
        'raw_response_sha256': digest(raw_response),
        'method': 'POST',
        'path': '/post/TABLE',
        'http_status': 200,
    }
    try:
        expected['signed_analysis_attestation_sha256'] = signed_attestation_hash(
            analysis_attestation, analysis_signature_hex)
    except (TypeError, ValueError, OverflowError):
        reasons.append('SIGNED_ANALYSIS_ATTESTATION_INVALID')
    for key, value in expected.items():
        if receipt.get(key) != value or (key == 'http_status' and type(receipt.get(key)) is not int):
            reasons.append('CAPTURE_BINDING_MISMATCH:' + key)

    sent = _utc(receipt.get('sent_at'))
    received = _utc(receipt.get('received_at'))
    analysis_done = _utc(envelope.get('analysis', {}).get('completed_at'))
    envelope_captured = _utc(envelope.get('result_response', {}).get('captured_at'))
    if not all((sent, received, analysis_done, envelope_captured)):
        reasons.append('CAPTURE_TIMESTAMPS_INVALID')
    elif not (analysis_done <= sent <= received == envelope_captured):
        reasons.append('CAPTURE_TIMESTAMPS_OUT_OF_ORDER')
    elif received - sent > timedelta(seconds=max_capture_duration_seconds):
        reasons.append('CAPTURE_DURATION_EXCEEDED')

    return {'status': 'OFFLINE_CAPTURE_RECEIPT_VALID' if not reasons else 'HOLD',
            'reasons': reasons, 'capture_id': capture_id if isinstance(capture_id, str) else None,
            'live_verified': False, 'engineering_accepted': False}


def verify_with_capture(
    envelope: dict, model_bytes: bytes, response_bytes: bytes,
    raw_request: bytes, analysis_attestation: dict, analysis_signature_hex: str,
    pinned_analysis_public_key: bytes, receipt: dict, receipt_signature_hex: str,
    pinned_collector_id: str, pinned_capture_public_key: bytes, *,
    previously_seen_capture_ids: AbstractSet[str] = frozenset(),
) -> dict:
    """Independent gates: base quality + signed analysis + request bytes + signed receipt."""
    prior = verify_all(envelope, model_bytes, response_bytes, raw_request,
                       analysis_attestation, analysis_signature_hex,
                       pinned_analysis_public_key)
    capture = verify_capture_receipt(
        envelope, raw_request, response_bytes, analysis_attestation,
        analysis_signature_hex, receipt, receipt_signature_hex,
        pinned_collector_id, pinned_capture_public_key,
        pinned_analysis_public_key,
        previously_seen_capture_ids=previously_seen_capture_ids,
    )
    return {
        'status': 'OFFLINE_EVIDENCE_GATES_PASS' if (
            prior['status'] == 'OFFLINE_EVIDENCE_GATES_PASS' and
            capture['status'] == 'OFFLINE_CAPTURE_RECEIPT_VALID') else 'HOLD',
        'reasons': prior['reasons'] + capture['reasons'],
        'capture_receipt_status': capture['status'],
        'prior_gate_status': prior['status'],
        'engineering_accepted': False,
        'live_verified': False,
        'note': 'A synthetic signature/capture fixture is NOT proof that MIDAS was accessed.'
    }
